### ISSUE TITLE
Requested updates to LiveGrid

### ISSUE THREAD

**Issue by awalter-bnl** [bluesky/bluesky#1095] opened 2018-09-18 18:45 UTC
# NOTE: This is being covered in PR #1098  
# Outline of scope
A number of new features/updates to LiveGrid have been requested. I have started this project in order to develop a plan to implement as much as possible. Listed below are the new features/upgrades to be added and some possible additional features (feel free to add others I may have missed). This is intended to start a discussion, and lead to a group conclusion on the what/when/how of implementing these changes.

## Additional features to be added:

1. Add the ability to define which scanned value is the x -axis and which is the y-axis.
    - This was requested by SMI in order to be able to swap which axis the 'inner motor' represents in grid scans.
     - We may want to us this feature to add some 'limited' multi dimensional plotting. (i.e. let the user select an x, a y and a z axis from a multi-dimensional scan to plot as a live grid plot.)
2. Add the actual trajectory on top of the image, see bluesky issue #1039 .
     - When a trajectory is known in advance we can overlay it onto the LiveGrid image.
     - It has been suggested (by @awalter-bnl) that we could use a colour change to show past/future points in the trajectory or remove already plotted points.
     - We could also update the readback position in the trajectory for all past points, overwriting the setpoint position.
3. Add the ability to switch between relative units and actual units for relative scans, see bluesky issue #1039.
     - At present it defaults to relative units as this is what is used to define extents.
4. Add the ability to define  arbitrary trajectories, see , see bluesky issue #1003, #1001 and #1061 
     - This will allow for square_spiral, and other arbitrary path scans that also result in a series of grid points, to use LiveGrid instead of LiveScatter.
     - @tacaswell suggested doing this by simply using the x and y co-ordinates from the event-source at each step to locate where to add the point on the grid.
     - Averaging if the point in the grid already contains a value will also allow all paths, regardless of if they result in a grid or not, to use LiveGrid.
     - This would also require passing in a 'raster shape' to indicate the size of the grid to be plotted against if the plan does not specify it.

## Possible extensions:

1. _Should we /How do we_ implement these proposed additions to BEC, I see two options (please add more if there are any) and they are not mutually exclusive:
    - through the inclusion of the optional kwargs in the metadata of the plan.
       - extents, shape, gridding, Ikey are all currently passed into Live_Grid in BEC through the start document in this way.
       - Has the benefit that the pre-defined plot parameters are stored in meta-data which allows for easy re-plotting later.
       - Is an easy solution for customizing at the plan level, it would be an easy UI for BL staff/ users to include md=(x_position='left') in the plan call to flip the x axis direction for instance.
       - perhaps the addition of a `plot_vars= ['axis1name', 'axis2name'] ` kwarg might supercede the 'hints' in order to allow for greater control of what is plotted? This may be a solution to the requests made by many BL staff to have more control over this.
       - With the current system for defining meta-data at various levels, this automatically includes a lot of flexibility, and may make the 'bec setup' file below redundant.
    - through a 'bec setup' file in the profile.
       - This provides a 'global' change to the settings for BEC, but probably makes changes for individual scan-types difficult.
       - potentially we could have different 'settings' for different scan-types (or other meta-data).
2. _Should we /How do we_ implement live adjustment of these parameters (something which has been requested several times by BL staff to me).
    - I suspect this is probably as simple as adding sliders, drop-down menus, etc.. widgets to the matplotlib figures and updating the plots based on changes to these although I have not yet attempted this so it could be more difficult than I suspect.
        - This would open the question of what items do we want 'live configurable'.
    - The real question is do we want to go down this route, are we considering introducing some of this functionality into a 'GUI'  in the future or do we prefer to let the BL staff come up with there own solutions?

**Comment by danielballan** [comment] 2018-09-19 14:10
> Should we /How do we implement these proposed additions to BEC,
> Should we /How do we implement live adjustment of these parameters (something which has been requested several times by BL staff to me).

This is where we are headed with the rewrite of the callbacks and BEC Let's push that discussion to a separate issue and focus this one on LiveGrid enhancements, with an eye toward maximum flexibility/generality/explicitness and all the dev-related concerns, punting usability to the next layer up.

**Comment by awalter-bnl** [comment] 2018-09-19 14:13
No Problem, At some point I would like to have some discussion about what changes are being made to BEC as I have no real idea.

This means that we will also need to punt item 3 as well as that is determined inside BEC.

**Comment by awalter-bnl** [comment] 2018-09-19 18:12
# Strategy for resolution.
This post is to outline the code approach that is intended to be used to resolve the scope described above. It is meant to invite suggestions/comments prior to implementing so please respond if you have any thoughts. Below I list 4 changes that I think will cover the items detailed in the scope. Number 1 is the only breaking change to the API, as I think it will require 2 new args.

I include some more detail below but a quick summary of the changes is:
## Summary:

1. update the event attribute of LiveGrid to place points on the plot based on the X and Y positions in doc['data']. 
    - This will require 2 new args `x` and  `y` which define which values from `doc['data']` to use for the axes units, similar to LiveScatter().
2. add `x_offset` and `y_offset` kwargs (default to zero) in order to shift the axis positions.
3. add `plan_pattern` kwarg (defaults as None) that, if not None, passes in the output of plan_patterns allowing LiveGrid to overlay the future path.
4. add a `past_path` kwarg (default as `False`) that, if `True`, overlays the actual positions as given by the `x` and `y` values in `doc['data']`.

## Outline:
### 1. Update the event attribute of mpl_plotting/LiveGrid to place the new intensity value at the point on the grid corresponding to `(doc['data'][self.x], doc['data'][self.y])`, averaging if that point is not nan.
- this uses information already provided to event in doc but requires two new args (`x` and `y` which are the  similar to what is currently used in LiveScatter).
- this removes any requirement that LiveGrid know the 'path' that the scan takes and hence allows arbitrary paths.
- this allows for paths that may hit the same point in the grid twice to work.
    - The plan would need to provide a 'shape' for the grid, which is only done currently for the 'grid path' scans like `grid_scan` and `square_spiral`.
- this allows for users to define any parameters from `doc['data']` (i.e. any read_attrs from either motors or detectors) that should be used for the x and y axis through the new arg's `x` and `y`.
    - hence define if the inner or outer motor is the x axis for instance.
    - would also allow for plotting of 'slices' through multi-dimensional (>2D) scans.
- NOTE: This will require a change to best-effort callbacks to ensure that 'extents' is always in absolute units (see item 2 for plotting in relative units)
    - This is required as LiveGrids event attribute does not receive any information regarding the relative positions only the absolute positions and so we should default to this.

### 2. Add x_offset and y_offset kwargs (defaults to zero), these will be used to shift the x and y axis units.
- These offsets will be added to the range values from 'extents' to determine the axes range and the x/y position values used to place the point on the grid in change 1 above.
- This can be used to switch between 'relative' and 'absolute' units for relative scans, as the correct offsets between the two can be fed into LiveGrid.

### 3. Add a 'plan_pattern' kwarg which, if not None, will feed in a cycler (list of dictionaries mapping motors to positions, matching the output of plan_patterns) that defines the path the plan will take.
- If this is not None this will then be used to generate an X, Y  array that will be plotted as markers with lines on the plot.
- In LiveGrid/event we should also remove the point that is being updated from the X-Y array.
- This will show the trajectory that the plan is yet to take.

### 4. Add a 'past_path' boolean kwarg (default as `False`).
- If this is `True` then create a zero length X,Y array and plot on the image using markers with lines.
- in the event attribute add the current point to the X-Y array
- This will show the path taken up to this point.
- I suspect this may also require us to add x and y kwargs like in change 1 above so we know what are the 'readback' as opposed to 'setpoint' values in `doc['data']`.

**Comment by bruceravel** [comment] 2018-09-21 19:01
FWIW, this:
```
   update the event attribute of LiveGrid to place points on the plot based on the X and Y 
   positions in doc['data'].

   This will require 2 new args x and y which define which values from doc['data'] to use 
   for the axes units, similar to LiveScatter().
```
is quite important to me. At my XAFS beamline, I regularly need to plot ratios of scalars. In my plans for doing 1D scans, I make extensive use of the `doc['data'][self.x]` and `doc['data'][self.x]` values.  I create lambda functions on the fly which make the needed ratios and pass those to a subs_decorator.

Being able to specify the `doc['data']`  values in that way is even more important for a LiveGrid -- particularly when the ring is in decay mode and I am normalizing a signal by the measurement of the incident beam intensity.

Just a long-winded way of say "thumbs up! please do that!"....

**Comment by prjemian** [comment] 2018-09-21 19:12
Couldn't you do the calculation(s) in EPICS and then use that result as an EpicsSignal?

**Comment by bruceravel** [comment] 2018-09-21 19:27
I presume Pete's question is directed at me.  Answer: Of course.  

The calculation could be done at many levels and there are arguments for and against.  However, as I started working through my problem, the number of combinations of choice of x-axis and calculations of things for the y-axis became unmanageably large.  Generating lambda functions on the fly on the basis of user input is way easier to maintain.  My beamline is "just an XAFS beamline" -- I don't need the most performant solution, but I certainly need a maintainable solution.

**Comment by prjemian** [comment] 2018-09-21 19:32
@bruceravel : That's right, the question was intended for you.  I understand the needs of "just an XAFS beamline" and it *does* come down to what is easier for *you* to maintain.  My vision was to have a single calc (or similar such as swait) record for the y-axis and configure it on the fly as you do the lambda function.  Seemed easier to maintain and easier for others to understand.  But that is just my POV.

**Comment by hhslepicka** [comment] 2018-09-21 19:38
Adding to Pete's comment: it is also very useful so you can see the same
information at display managers such as PyDM, CS-Studio, EDM, MEDM and etc.

**Comment by danielballan** [comment] 2018-09-24 14:10
The "party line" from DAMA on these questions is, "We should make it easy to prototype this in Python, but socially encourage folks to push these computations down to the IOC layer if they become stable 'services' that aren't the subject of frequent iteration/experimentation," for exactly the reason that @hhslepicka gave.

**Comment by prjemian** [comment] 2018-09-24 14:18
+1  -- Compute it one place, watch the exact same value from many.  *Prototype in a client of convenience until the method is stable, then implement in IOC* has been our mantra for decades.

**Comment by awalter-bnl** [comment] 2018-09-26 11:12
An update on this, after consideration of the new RunEngine and Callback refactor that we expect to be out soon the plan has shifted to writing a new version of LiveGrid that works with the new API structure. It is expected that all of the changes discussed here will be included in this new version, however the exact API is still a work in progress. 

I will update here again once we have some more info on this.

**Comment by stan-dot** [comment] 2024-08-06 09:44
@awalter-bnl any updates? 

https://github.com/bluesky/bluesky/issues/1095#issuecomment-424677191

**Comment by awalter-bnl** [comment] 2024-08-06 11:30
@stan-dot , I suspect that development has long surpassed this PR. I am happy to close this out if others agree

**Comment by stan-dot** [comment] 2024-08-06 14:42
@tacaswell , @danielballan  , @prjemian ?

**Comment by prjemian** [comment] 2024-08-07 20:48
I'm OK to close this one.

**Closed** 2024-08-08 08:32 UTC
Labels: python, plotting
