### ISSUE TITLE
Verbosity flags in bluesky-0MQ-proxy CLI tool are not respected.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1438] opened 2021-02-17 22:16 UTC
## Bug Report

Formerly,

```
bluesky-0MQ-proxy 5577 5578 -v
```

would write log messages to help debug data flow through the network. Now, no logs appear.

## Possible Solution

I suspect the changes to logging in bluesky about a year ago created this bug and it wasn't noticed until now.

## Steps to Reproduce (for bugs)

Follow this example https://blueskyproject.io/bluesky/callbacks.html#subscriptions-in-separate-processes-or-host-with-0mq

and feed the `RE` a plan like

```py
from bluesky.plans import count
RE(count([]))  # emits a 'start' and 'stop' doc

## Context

This was noticed during a group-coding session at ALS. Both @JulReinhardt and @danielballan reproduced the issue.

**Comment by dmgav** [comment] 2021-02-18 19:55
The issue is resolved in PR https://github.com/bluesky/bluesky/pull/1439

**Closed by dmgav** 2021-02-18 19:55 UTC
