### ISSUE TITLE
Refactor: Separate I/O bundling code from interruption handling code.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#832] opened 2017-09-10 22:54 UTC
This refactor will make the monolithic RunEngine class easier to maintain by breaking it up into pieces. Initial conversations about how this could be done suggest that it can be done in a way that does not break the user-facing API.

**Comment by danielballan** [comment] 2017-12-15 13:39
Note: @teddyrendahl casually pitched the idea of threading in-line analysis through a Device-like interface and into a separate RunEngine owned by the plan. While a second RunEngine may be overkill in my opinion, using EventBundler on its own could be helpful. Thus, exposing the event-bundling logic in a reusable, modular way may have utility beyond just code readability.

**Comment by danielballan** [comment] 2018-07-30 16:34
Related: https://github.com/NSLS-II/bluesky/issues/1074

**Comment by tacaswell** [comment] 2019-05-15 15:52
closing as duplicate of #585

**Closed by tacaswell** 2019-05-15 15:52 UTC
Labels: maintenance
