### ISSUE TITLE
print_summary fails for some cases using peaks keys

### ISSUE THREAD

**Issue by ambarb** [bluesky/bluesky#1017] opened 2018-04-08 04:49 UTC
when using `mv()` that points to a value in peaks, is it possible to print the specific key names instead of printing out its last known value?  Users should see if they typed the correct detector and the correct key ('cen' vs 'max')

**Comment by ambarb** [comment] 2018-04-15 01:29
As a bonus, if we use a read_atrribute name in print_summary that is not in the current peaks dictionary, then print_summary fails. ;(   We have to run a junk scan with the detector we plan on using in print_summary

**Comment by tacaswell** [comment] 2018-04-18 20:38
I don't quite understand, can you hive an example plan that is failing?

**Comment by ambarb** [comment] 2018-04-18 20:49
We are taking data right now.  I will past an example ASAP.  I am confident that we can reproduce.

The problem comes in when  you are switching between detectors from scan_plan to scan_plan

**Comment by ambarb** [comment] 2018-07-28 17:54
Hi Guys,  I didn't provide evidence, but we can make it happen at will at 2ID if you want to come and see.  It is just the print summary that gets mad. For now, we comment out the things that use peaks and try to remember to uncomment when we are ready for the RunEngine

@bisogni FYI

**Comment by awalter-bnl** [comment] 2019-01-24 21:06
FYI I have also been able to reproduce the issue using the attached file.

starting python and then doing %run on the attached file sets up the test.
calling `summarize_plan(test_plan())` without having run the plan in a run Engine throws a `KeyError` exception as the dictionary `bec.peaks.cen` does not yet have an entry for the key `det`.

subsequently running the scan via `RE(test_plan())` will work as expected.

calling `summarize_plan(test_plan())` after this will work, however for each of the `yield from mv(....)` lines in the plan it just indicates that the move will occur too the current value of the dict `bec.peaks.cen['motor']` which is a little misleading.

The solution to this, I think, is similar to the solution proposed for issue #1016 . Here, inside `summarize_plan` or an equivalent simulator we need to introspect the arguments to the `yield from mv(....)` command and if the 'value' is returned from a call to the `bec.peaks` dict then we should print the string "bec.peaks..." instead of the value. I am not sure if this is even technically possible but I don't see a better solution.

[summarize_plan_test_2.zip](https://github.com/NSLS-II/bluesky/files/2793618/summarize_plan_test_2.zip)

**Comment by danielballan** [comment] 2019-01-25 16:17
Here is @awalter-bnl in line for more convenient reference:

<details>

```py
from bluesky.plans import scan, rel_scan
from bluesky.plan_stubs import mv
from ophyd.sim import hw
from bluesky import RunEngine
from bluesky.callbacks.best_effort import BestEffortCallback
from bluesky.simulators import summarize_plan

RE=RunEngine()
hw=hw()
bec=BestEffortCallback()
RE.subscribe(bec)
hw.det.kind='hinted'
hw.motor.kind='hinted'

def test_plan():
    '''this is a test plan with the correct syntax for summarize_plan.
    '''

    yield from scan([hw.det], hw.motor, -5, 5, 5,
                    md={'reason':'attempt to cause issues'})

    yield from mv(hw.motor, bec.peaks.cen['det'])

    yield from rel_scan([hw.det], hw.motor, -1, 1, 5,
                    md={'reason':'attempt to cause issues'})

    yield from mv(hw.motor, bec.peaks.cen['det'])
```

</details>

> calling summarize_plan(test_plan()) after this will work, however for each of the yield from mv(....) lines in the plan it just indicates that the move will occur too the current value of the dict bec.peaks.cen['motor'] which is a little misleading.

I can see why that's potentially confusing, but it is indeed what the plan would do. If your plan depends on mutable state, such as `bec.peaks['cen']`, then the result from `summarize_plan` naturally changes when that mutable state changes. In the same way that `summarize_plan` does not work on adaptive plans, it also cannot work on plans whose behavior depends on measurements that haven't yet been taken.

> Here, inside summarize_plan or an equivalent simulator we need to introspect the arguments to the yield from mv(....) command and if the 'value' is returned from a call to the bec.peaks dict then we should print the string "bec.peaks...

This kind of introspection is not technically possible in Python. I'm going to tentatively close this issue because I don't think it's actionable.

**Comment by tacaswell** [comment] 2019-01-25 17:22
The plan should be more defensive about detecting if it is 'live' or being run through a simulator.

**Comment by danielballan** [comment] 2019-01-25 19:16
We have an issue for that: https://github.com/NSLS-II/bluesky/issues/1035

**Comment by awalter-bnl** [comment] 2019-01-25 19:53
@ambarb just stopped by my office to discuss this issue. she accepts that we can't deal with the point made by @danielballan above but was hoping we could deal with the first issue:

> calling summarize_plan(test_plan()) without having run the plan in a run Engine throws a KeyError exception as the dictionary bec.peaks.cen does not yet have an entry for the key det.

I agreed to look into wrapping this in a `try: except: ` block to handle this kind of error but warned her that it may be too general of an error to do this.

I will re-open this issue while I work through that.

**Comment by tacaswell** [comment] 2019-01-25 21:58
You have to make your plan a bit more defensive

```python
from ophyd.sim import hw
import bluesky.plans as bp
import bluesky.plan_stubs as bps
import bluesky.preprocessors as bpp
from bluesky.callbacks.fitting import PeakStats
from bluesky.run_engine import RunEngine
from bluesky.simulators import print_summary
from bluesky.callbacks.best_effort import BestEffortCallback

bec = BestEffortCallback()
RE = RunEngine()
RE.subscribe(bec)

HW = hw()

def my_defensive_plan(det, motor, start, stop, step):
    ps = PeakStats(motor.name, det.name)
    
    uid = yield from bpp.subs_wrapper(
        bp.scan([det], motor, start, stop, step),
        ps)

    if uid is not None:
        target = ps.cen
    else:
        target = 'CENTER'

    yield from bps.mov(motor, target)
    return uid


RE(my_defensive_plan(HW.det, HW.motor, -1, 1, 10))
print_summary(my_defensive_plan(HW.det, HW.motor, -1, 1, 10))
```

which prints out

```
=================================== Open Run ===================================
motor -> -1.0
  Read ['det', 'motor']
motor -> -0.7777777777777778
  Read ['det', 'motor']
motor -> -0.5555555555555556
  Read ['det', 'motor']
motor -> -0.33333333333333337
  Read ['det', 'motor']
motor -> -0.11111111111111116
  Read ['det', 'motor']
motor -> 0.11111111111111116
  Read ['det', 'motor']
motor -> 0.33333333333333326
  Read ['det', 'motor']
motor -> 0.5555555555555554
  Read ['det', 'motor']
motor -> 0.7777777777777777
  Read ['det', 'motor']
motor -> 1.0
  Read ['det', 'motor']
================================== Close Run ===================================
motor -> CENTER
Transient Scan ID: 1     Time: 2019/01/25 16:57:15
Persistent Unique Scan ID: '5bfcf293-703d-4e03-8257-af5a235faa17'
New stream: 'primary'
+-----------+------------+------------+
|   seq_num |       time |      motor |
+-----------+------------+------------+
|         1 | 16:57:15.8 |     -1.000 |
|         2 | 16:57:15.8 |     -0.778 |
|         3 | 16:57:15.8 |     -0.556 |
|         4 | 16:57:15.8 |     -0.333 |
|         5 | 16:57:15.8 |     -0.111 |
|         6 | 16:57:15.9 |      0.111 |
|         7 | 16:57:15.9 |      0.333 |
|         8 | 16:57:15.9 |      0.556 |
|         9 | 16:57:15.9 |      0.778 |
|        10 | 16:57:15.9 |      1.000 |
+-----------+------------+------------+
generator scan ['5bfcf293'] (scan num: 1)
```

In #1035 we are talking about a protocol for the thing running the plan to report more about its self to the plan, but for now the easiest thing to do is to just check if something you expect to return a non-trivial value returns `None` which lets the plan know it is being iterated through (as 
```python
for msg in plan:
   ...
``` 
is the same as 

```python
itr = iter(gen)
while True: 
    try: 
        lhs = itr.send(None) 
    except StopIteration: 
        break
```

**Comment by tacaswell** [comment] 2019-05-15 17:49
@ambarb Closing this is stale, please re-open if you think we need to do more here.

**Closed by tacaswell** 2019-05-15 17:49 UTC

**Comment by ambarb** [comment] 2019-05-15 20:08
It is a problem, and to deal with this we just hope that it works and not run `print_summary` or comment out those lines with `yield from mv(motor1, peaks.det1['cen])` just for `print_summary()`, etc

I just want people that use spec to feel that things are not "missing" and this is why I brought it up.  If you someone is doing a temperature dependent measurement and are trying to keep track of a Bragg peak for something that has a large thermal expansion coefficient, then this adaptability to find the center/maximum is something that has to happen.

**Comment by ambarb** [comment] 2019-05-15 20:09
Also, it is used for "aligning the beamline"

**Comment by ambarb** [comment] 2019-07-11 14:36
@mrakitin @ambarb please see this discussion to understand why this issue has not been addressed
